before_script:
  - apt-get update -yq
  - apt-get install -y zip
  - apt-get install -y p7zip
  - apt-get install -y unzip
  - apt-get install -y cmake
  - apt-get install -y valgrind
  - apt-get install -y libtbb-dev
  - make; cd src; make chico; cd ..;

compile_and_test:
  script:
    - cd test_scripts; ./validate_fmi.sh; ./validate_bio_normal.sh; ./validate_bio_detail.sh; cd ..;
    - cd ext/LZ/RLZ_parallel/src/; ./validate_plain.sh; ./validate_fasta.sh; cd ../../../../;
